databases:
  - name: luminousdb
    plan: free
    databaseName: ecosystem
    user: luminous

services:
  - type: web
    plan: free
    name: luminousEcosystem
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn luminousEcosystem.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: luminousdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4